version: '3'
services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/data/postgresql.db

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres